// AyurSutra Clinical, Panchakarma, and Billing & Invoices Data Model

export const initialPatients = [
  {
    id: 'AY-2026-001',
    name: 'Ananya Sharma',
    age: 34,
    gender: 'Female',
    contact: '+91 98765 43210',
    dosha: 'Vata-Pitta',
    doshaBalance: { vata: 55, pitta: 35, kapha: 10 },
    currentTherapy: 'Shirodhara & Abhyanga',
    phase: 'Pradhana Karma',
    dayCount: 'Day 4 of 7',
    progressPercent: 57,
    status: 'In Progress',
    room: 'Chikitsa Suite 2',
    therapist: 'Dr. Ramesh Vaidya',
    nadiPulse: 'Vata-Pitta (Chapa & Sarpa Gati)',
    formulations: ['Mahanarayana Taila', 'Ksheerabala 101 Drops', 'Brahmi Ghrita'],
    diet: 'Samsarjana Stage 2 (Mudga Yusha - Green Gram Soup with Cumin & Ghee)',
    notes: 'Significant relief in chronic migraines and sleep dysregulation. Shirodhara oil temperature strictly 38.5°C.'
  },
  {
    id: 'AY-2026-002',
    name: 'Rajesh Verma',
    age: 48,
    gender: 'Male',
    contact: '+91 91234 56789',
    dosha: 'Kapha Predominant',
    doshaBalance: { vata: 15, pitta: 25, kapha: 60 },
    currentTherapy: 'Vamana Karma Prep',
    phase: 'Purva Karma',
    dayCount: 'Day 2 of 5',
    progressPercent: 40,
    status: 'Scheduled',
    room: 'Karma Hall A',
    therapist: 'Vaidya Sneha Nair',
    nadiPulse: 'Kapha (Mando Gati / Hamsa)',
    formulations: ['Sukumara Ghrita', 'Pippali Churna', 'Triphala Kashayam'],
    diet: 'Deepana-Pachana (Hot Water with Ginger & Honey, Light Peya)',
    notes: 'Snehapana dose increased to 60ml. Digestibility being monitored every 3 hours.'
  },
  {
    id: 'AY-2026-003',
    name: 'Sunita Joshi',
    age: 52,
    gender: 'Female',
    contact: '+91 99887 76655',
    dosha: 'Pitta-Vata',
    doshaBalance: { vata: 40, pitta: 50, kapha: 10 },
    currentTherapy: 'Kashaya & Sneha Basti',
    phase: 'Pradhana Karma',
    dayCount: 'Day 6 of 8',
    progressPercent: 75,
    status: 'In Progress',
    room: 'Recovery Room 1',
    therapist: 'Dr. Ramesh Vaidya',
    nadiPulse: 'Pitta (Manduka Gati)',
    formulations: ['Dhanwantharam 101', 'Sahacharadi Kashayam', 'Chandanadi Oil'],
    diet: 'Cooling Pitta-pacifying diet with boiled rice and Amalaki ghrita',
    notes: 'Joint inflammation reduced by 60%. Good retention time for Anuvasana Basti (4.5 hours).'
  },
  {
    id: 'AY-2026-004',
    name: 'Vikramaditya Rao',
    age: 41,
    gender: 'Male',
    contact: '+91 94455 66778',
    dosha: 'Tridoshic (V-P-K)',
    doshaBalance: { vata: 35, pitta: 35, kapha: 30 },
    currentTherapy: 'Nasya & Shirovasti',
    phase: 'Pradhana Karma',
    dayCount: 'Day 3 of 7',
    progressPercent: 42,
    status: 'In Progress',
    room: 'Chikitsa Suite 1',
    therapist: 'Vaidya Harish Chandra',
    nadiPulse: 'Tridosha Samata',
    formulations: ['Anu Taila', 'Karpasastyadi Tailam', 'Ashwagandharishta'],
    diet: 'Laghu Ahara (Warm barley gruel with roasted jeera)',
    notes: 'Sinus clearance confirmed. Administering 8 drops of Anu Taila per nostril with steam.'
  },
  {
    id: 'AY-2026-005',
    name: 'Meera Nambiar',
    age: 29,
    gender: 'Female',
    contact: '+91 97711 22334',
    dosha: 'Vata Predominant',
    doshaBalance: { vata: 65, pitta: 20, kapha: 15 },
    currentTherapy: 'Takradhara & Rasayana',
    phase: 'Paschat Karma',
    dayCount: 'Day 7 of 7',
    progressPercent: 100,
    status: 'Completed',
    room: 'Recovery Suite 3',
    therapist: 'Vaidya Sneha Nair',
    nadiPulse: 'Vata pacified (Samana Vayu)',
    formulations: ['Chyawanprash Awaleha', 'Kalyanaka Ghrita', 'Dashamularishta'],
    diet: 'Rasayana regenerative diet, warm organic milk with saffron and cardamom',
    notes: 'Full cycle completed successfully. Stress markers normalized. Discharging tomorrow with home protocol.'
  },
  {
    id: 'AY-2026-006',
    name: 'Arjun Singhania',
    age: 56,
    gender: 'Male',
    contact: '+91 98822 33445',
    dosha: 'Pitta-Kapha',
    doshaBalance: { vata: 15, pitta: 50, kapha: 35 },
    currentTherapy: 'Virechana Karma',
    phase: 'Pradhana Karma',
    dayCount: 'Day 5 of 6',
    progressPercent: 83,
    status: 'In Progress',
    room: 'Chikitsa Suite 3',
    therapist: 'Dr. Ramesh Vaidya',
    nadiPulse: 'Pitta-Tikshna',
    formulations: ['Trivrit Lehyam', 'Avipattikar Churna', 'Amruthotharam Kashaya'],
    diet: 'Strict boiled rice water (Vilepi) with roasted pomegranate seeds',
    notes: 'Virechana vega count reached 12 bouts smoothly. Adequate hydration maintained.'
  }
];

export const scheduledTherapies = [
  { id: 1, time: '08:00 AM', patient: 'Ananya Sharma', therapy: 'Abhyanga (Herbal Medicated Massage)', room: 'Chikitsa Suite 2', therapist: 'Vaidya Sneha', phase: 'Purva' },
  { id: 2, time: '09:30 AM', patient: 'Ananya Sharma', therapy: 'Shirodhara (Takradhara Protocol)', room: 'Chikitsa Suite 2', therapist: 'Vaidya Sneha', phase: 'Pradhana' },
  { id: 3, time: '10:45 AM', patient: 'Vikramaditya Rao', therapy: 'Nasya (Pratimarsa Nasya Karma)', room: 'Chikitsa Suite 1', therapist: 'Vaidya Harish', phase: 'Pradhana' },
  { id: 4, time: '11:30 AM', patient: 'Rajesh Verma', therapy: 'Snehapana (Internal Oleation Ghee)', room: 'Karma Hall A', therapist: 'Dr. Ramesh', phase: 'Purva' },
  { id: 5, time: '02:00 PM', patient: 'Sunita Joshi', therapy: 'Kashaya Basti (Herbal Decoction Enema)', room: 'Recovery Room 1', therapist: 'Dr. Ramesh', phase: 'Pradhana' },
  { id: 6, time: '04:30 PM', patient: 'Meera Nambiar', therapy: 'Samsarjana Krama Diet Consultation', room: 'Consultation Room 3', therapist: 'Vaidya Sneha', phase: 'Paschat' }
];

export const chikitsaRooms = [
  { id: 'RM-101', name: 'Chikitsa Suite 1', type: 'Shirodhara & Head Therapies', status: 'Occupied', patient: 'Vikramaditya Rao', oilTemp: '38.2°C', heater: 'Active', ambient: '24°C / 45% RH' },
  { id: 'RM-102', name: 'Chikitsa Suite 2', type: 'Full Body Abhyanga & Takradhara', status: 'Occupied', patient: 'Ananya Sharma', oilTemp: '39.0°C', heater: 'Active', ambient: '25°C / 48% RH' },
  { id: 'RM-103', name: 'Karma Hall A', type: 'Purva Karma & Vamana Facility', status: 'In Preparation', patient: 'Rajesh Verma', oilTemp: '37.5°C', heater: 'Pre-heating', ambient: '23°C / 50% RH' },
  { id: 'RM-104', name: 'Chikitsa Suite 3', type: 'Virechana & Basti Sanctuary', status: 'Occupied', patient: 'Arjun Singhania', oilTemp: '38.0°C', heater: 'Active', ambient: '24°C / 46% RH' },
  { id: 'RM-105', name: 'Swedana Steam Chamber', type: 'Nadi & Bashpa Swedan', status: 'Available', patient: 'None (Sanitized)', oilTemp: 'Ready', heater: 'Standby', ambient: '22°C / 40% RH' },
  { id: 'RM-106', name: 'Recovery Sanctuary', type: 'Post-Karma Deep Rest & Samsarjana', status: 'Occupied', patient: 'Meera Nambiar', oilTemp: 'N/A', heater: 'Off', ambient: '23.5°C / 52% RH' }
];

export const ayurvedicElements = [
  { name: 'Prithvi', english: 'Earth', sanskrit: 'पृथिवी', dosha: 'Kapha', color: '#eab308', geometry: 'Cube / Stambha', property: 'Stability, Density & Structure' },
  { name: 'Jala', english: 'Water', sanskrit: 'जल', dosha: 'Kapha-Pitta', color: '#06b6d4', geometry: 'Icosahedron / Drava', property: 'Cohesion, Fluidity & Moisture' },
  { name: 'Agni', english: 'Fire', sanskrit: 'अग्नि', dosha: 'Pitta', color: '#f97316', geometry: 'Tetrahedron / Tejas', property: 'Transformation, Metabolism & Vision' },
  { name: 'Vayu', english: 'Air', sanskrit: 'वायु', dosha: 'Vata', color: '#10b981', geometry: 'Octahedron / Chala', property: 'Movement, Respiration & Nerve Pulses' },
  { name: 'Akasha', english: 'Ether / Space', sanskrit: 'आकाश', dosha: 'Vata', color: '#a855f7', geometry: 'Dodecahedron / Avakasha', property: 'Consciousness, Channels & Sound' }
];

// ============================================================================
// AYURSUTRA BILLING, INVOICE & PAYMENT DATA MODEL
// ============================================================================

export const initialInvoices = [
  {
    id: 'INV-2026-101',
    patientId: 'AY-2026-001',
    patientName: 'Ananya Sharma',
    contact: '+91 98765 43210',
    date: '2026-08-16',
    dueDate: '2026-08-20',
    doctorName: 'Dr. Ramesh Vaidya',
    packageTitle: '7-Day Shirodhara & Abhyanga Intensive Package',
    status: 'Paid',
    paymentMethod: 'UPI (GPay / PhonePe)',
    transactionId: 'TXN-AYUR-882194',
    paidAt: '2026-08-16 10:45 AM',
    items: [
      { description: 'Shirodhara Medicated Therapy (7 Sessions)', qty: 7, rate: 3500, amount: 24500 },
      { description: 'Sarvanga Abhyanga Medicated Massage (7 Sessions)', qty: 7, rate: 2200, amount: 15400 },
      { description: 'Ksheerabala 101 & Mahanarayana Tailam', qty: 2, rate: 1850, amount: 3700 },
      { description: 'Senior Acharya Initial Consult & Nadi Pariksha', qty: 1, rate: 1500, amount: 1500 },
      { description: 'Chikitsa Suite 2 Room Facility (4 Days Inpatient)', qty: 4, rate: 3000, amount: 12000 }
    ],
    subtotal: 57100,
    gstPercent: 5,
    taxGst: 2855,
    discount: 2000,
    totalAmount: 57955,
    amountPaid: 57955,
    balanceDue: 0
  },
  {
    id: 'INV-2026-102',
    patientId: 'AY-2026-002',
    patientName: 'Rajesh Verma',
    contact: '+91 91234 56789',
    date: '2026-08-17',
    dueDate: '2026-08-22',
    doctorName: 'Vaidya Sneha Nair',
    packageTitle: '5-Day Purva Karma & Vamana Shodhana Protocol',
    status: 'Pending',
    paymentMethod: 'Pending Payment',
    transactionId: 'N/A',
    paidAt: 'Unpaid',
    items: [
      { description: 'Snehapana Internal Oleation with Sukumara Ghrita', qty: 5, rate: 2400, amount: 12000 },
      { description: 'Swedana Herbal Steam Chamber Facility', qty: 3, rate: 1800, amount: 5400 },
      { description: 'Vamana Karma Classical Shodhana Session', qty: 1, rate: 8500, amount: 8500 },
      { description: 'Classical Triphala & Pippali Formulations', qty: 1, rate: 2100, amount: 2100 }
    ],
    subtotal: 28000,
    gstPercent: 5,
    taxGst: 1400,
    discount: 1000,
    totalAmount: 28400,
    amountPaid: 0,
    balanceDue: 28400
  },
  {
    id: 'INV-2026-103',
    patientId: 'AY-2026-003',
    patientName: 'Sunita Joshi',
    contact: '+91 99887 76655',
    date: '2026-08-15',
    dueDate: '2026-08-19',
    doctorName: 'Dr. Ramesh Vaidya',
    packageTitle: '8-Day Kashaya & Sneha Basti Protocol',
    status: 'Paid',
    paymentMethod: 'HDFC Credit Card (•••• 4092)',
    transactionId: 'TXN-AYUR-773821',
    paidAt: '2026-08-15 03:20 PM',
    items: [
      { description: 'Kashaya Basti Decoction Administration (4 Sessions)', qty: 4, rate: 3200, amount: 12800 },
      { description: 'Anuvasana Sneha Basti (4 Sessions)', qty: 4, rate: 2800, amount: 11200 },
      { description: 'Dhanwantharam 101 & Sahacharadi Formulations', qty: 1, rate: 3400, amount: 3400 },
      { description: 'Recovery Room Inpatient Stay (6 Days)', qty: 6, rate: 2500, amount: 15000 }
    ],
    subtotal: 42400,
    gstPercent: 5,
    taxGst: 2120,
    discount: 1500,
    totalAmount: 43020,
    amountPaid: 43020,
    balanceDue: 0
  },
  {
    id: 'INV-2026-104',
    patientId: 'AY-2026-004',
    patientName: 'Vikramaditya Rao',
    contact: '+91 94455 66778',
    date: '2026-08-17',
    dueDate: '2026-08-21',
    doctorName: 'Vaidya Harish Chandra',
    packageTitle: '7-Day Nasya & Shirovasti Neurological Care',
    status: 'Pending',
    paymentMethod: 'Ayush TPA Insurance Claim (Star Health)',
    transactionId: 'TPA-CLAIM-44812',
    paidAt: 'Processing Claim',
    items: [
      { description: 'Pratimarsa & Marsha Nasya Karma Therapy', qty: 7, rate: 1800, amount: 12600 },
      { description: 'Shirovasti Medicated Cap Retention Therapy', qty: 3, rate: 4200, amount: 12600 },
      { description: 'Anu Taila & Karpasastyadi Herbal Extracts', qty: 1, rate: 2800, amount: 2800 },
      { description: 'Chikitsa Suite 1 Chamber Allocation (3 Days)', qty: 3, rate: 3000, amount: 9000 }
    ],
    subtotal: 37000,
    gstPercent: 5,
    taxGst: 1850,
    discount: 0,
    totalAmount: 38850,
    amountPaid: 0,
    balanceDue: 38850
  },
  {
    id: 'INV-2026-105',
    patientId: 'AY-2026-005',
    patientName: 'Meera Nambiar',
    contact: '+91 97711 22334',
    date: '2026-08-14',
    dueDate: '2026-08-18',
    doctorName: 'Vaidya Sneha Nair',
    packageTitle: 'Complete 7-Day Rasayana Rejuvenation Cycle',
    status: 'Paid',
    paymentMethod: 'Net Banking (SBI Bank)',
    transactionId: 'TXN-AYUR-661902',
    paidAt: '2026-08-14 11:10 AM',
    items: [
      { description: 'Takradhara Medicated Buttermilk Stream (7 Sessions)', qty: 7, rate: 3200, amount: 22400 },
      { description: 'Rasayana Organic Rejuvenation Diet & Formulations', qty: 1, rate: 6500, amount: 6500 },
      { description: 'Gold Grade Chyawanprash & Brahmi Rasayana', qty: 2, rate: 2200, amount: 4400 },
      { description: 'Recovery Sanctuary VIP Suite (7 Days)', qty: 7, rate: 3500, amount: 24500 }
    ],
    subtotal: 57800,
    gstPercent: 5,
    taxGst: 2890,
    discount: 3000,
    totalAmount: 57690,
    amountPaid: 57690,
    balanceDue: 0
  },
  {
    id: 'INV-2026-106',
    patientId: 'AY-2026-006',
    patientName: 'Arjun Singhania',
    contact: '+91 98822 33445',
    date: '2026-08-17',
    dueDate: '2026-08-23',
    doctorName: 'Dr. Ramesh Vaidya',
    packageTitle: '6-Day Classical Virechana Shodhana Karma',
    status: 'Paid',
    paymentMethod: 'UPI (Paytm / BHIM)',
    transactionId: 'TXN-AYUR-994012',
    paidAt: '2026-08-17 09:15 AM',
    items: [
      { description: 'Virechana Karma Preparation & Purgation Session', qty: 1, rate: 7500, amount: 7500 },
      { description: 'Abhyanga & Swedana Pre-Karma (4 Sessions)', qty: 4, rate: 2200, amount: 8800 },
      { description: 'Trivrit Lehyam & Classical Kashayam Package', qty: 1, rate: 3200, amount: 3200 },
      { description: 'Chikitsa Suite 3 Private Room (5 Days)', qty: 5, rate: 3000, amount: 15000 }
    ],
    subtotal: 34500,
    gstPercent: 5,
    taxGst: 1725,
    discount: 1500,
    totalAmount: 34725,
    amountPaid: 34725,
    balanceDue: 0
  }
];

export const pricingCatalog = [
  { code: 'TH-01', name: 'Shirodhara Medicated Therapy', type: 'Therapy', price: 3500, gst: 5 },
  { code: 'TH-02', name: 'Sarvanga Abhyanga Massage', type: 'Therapy', price: 2200, gst: 5 },
  { code: 'TH-03', name: 'Vamana Karma Full Procedure', type: 'Therapy', price: 8500, gst: 5 },
  { code: 'TH-04', name: 'Virechana Karma Shodhana', type: 'Therapy', price: 7500, gst: 5 },
  { code: 'TH-05', name: 'Kashaya / Sneha Basti', type: 'Therapy', price: 3200, gst: 5 },
  { code: 'TH-06', name: 'Nasya & Shirovasti Karma', type: 'Therapy', price: 2800, gst: 5 },
  { code: 'TH-07', name: 'Takradhara Buttermilk Protocol', type: 'Therapy', price: 3200, gst: 5 },
  { code: 'CS-01', name: 'Senior Vaidya Nadi Pariksha Consult', type: 'Consultation', price: 1500, gst: 0 },
  { code: 'CS-02', name: 'Follow-up Clinical Review', type: 'Consultation', price: 800, gst: 0 },
  { code: 'MED-01', name: 'Ksheerabala 101 Drops (50ml)', type: 'Pharmacy', price: 1850, gst: 5 },
  { code: 'MED-02', name: 'Mahanarayana Tailam (500ml)', type: 'Pharmacy', price: 1200, gst: 5 },
  { code: 'MED-03', name: 'Gold Grade Chyawanprash (1kg)', type: 'Pharmacy', price: 1450, gst: 5 },
  { code: 'RM-01', name: 'Chikitsa Private Suite (Per Day)', type: 'Room', price: 3000, gst: 5 }
];
